spring.application.name=CompanyApp

# db - PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/company
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# H2
spring.h2.console.enabled=true

# Liquibase
spring.liquibase.change-log=classpath:db.changelog/db.changelog.xml


# Swagger / OpenAPI
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

# to delete
spring.main.allow-bean-definition-overriding=true
jwtSigningKey=4A614E645267556B58703273357638792F423F4528482B4B6250655368566D597133743677397A24432646294A404E635166546A576E5A723475377821412544


