package com.company.CompanyApp.model;

public enum ActionType {
    // adding
    ADDING_CONSTRUCTION,
    ADDING_CUSTOMER,
    ADDING_MATERIAL,
    ADDING_TASK,

    // deleting
    DELETING_CUSTOMER,
    DELETING_CONSTRUCTION,
    DELETING_MATERIAL,
    DELETING_TASK,

    // updating
    UPDATE_CUSTOMER,
    UPDATE_CONSTRUCTION,
    UPDATE_MATERIAL,
    UPDATE_TASK,

    // retrieving
    RETRIEVING_ALL_CUSTOMERS,
    RETRIEVING_ALL_CONSTRUCTIONS,
    RETRIEVING_ALL_MATERIALS,
    RETRIEVING_ALL_ACTIONS,
    RETRIEVING_ALL_TASKS,
    RETRIEVING_ALL_CUSTOMERS_FROM_CONSTRUCTION,
    RETRIEVING_ALL_TASKS_FROM_CONSTRUCTION,
    RETRIEVING_MOST_EXPENSIVE_TASK_FROM_CONSTRUCTION,
    RETRIEVING_PERCENT_OF_REALIZATION,

    // edit
    EDIT,

    // account operation
    ENABLE_CUSTOMER_ACCOUNT,
    DISABLE_CUSTOMER_ACCOUNT,
    LOCK_CUSTOMER_ACCOUNT,
    UNLOCK_CUSTOMER_ACCOUNT



}
